# Copyright 2013 Daniel Ramirez (javamonn@gmail.com)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE file.
#

# Waf build script for an RTEMS Hello
import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)
    bld.includes = ['../support']
    bld(features = 'c cprogram',
        target = 'semaphore-shuffle.exe',
        includes = bld.includes,
        source = ['semaphore-shuffle.c'])
