# Copyright 2014 Daniel Ramirez
#
# This file's license is 2-clause BSD as in this distribution's LICENSE file.
#

# Waf build script for an RTEMS Hello
import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)
    bld.includes = ['../support']
    bld(features = 'c cprogram',
        target = 'deadlock-break.exe',
        includes = bld.includes,
        source = ['deadlock-break.c'])
